### ISSUE TITLE
Problems with running test.py

### ISSUE THREAD

**Issue by hy2292** [mfazampour/ProRegGAN#2]
When I run test.py, it shows No module named " models.test_model ". When I use the model during training (add --model cut3d_multitask in the command line), the program cannot run correctly. It displays an error: 'CUT3DmultiTaskModel' object has no attribute netD (but netD is not required during the test phase).Is the test model missing or is my method wrong? I hope to get an answer, thank you very much :D

**Comment by Hongzunhei** [comment]
I have also encountered this problem. Have you solved it？

**Comment by mfazampour** [comment]
I will check into it this week, update the readme and fix this issue.

**Comment by Hongzunhei** [comment]
> 我将在本周检查它，更新自述文件并解决此问题。

That's wonderful news! I would be extremely grateful if you could fix the source code. Your paper is truly excellent and has made a significant contribution to the field. I hope to learn more from you.

Thank you very much for your help.
